src/index.js
test/api_test.js

Preserve Kinto.js expected batch behavior.

---

src/index.js
test/integration_test.js

This allows retrieving the list of records for a given collection from a given bucket.

Add get_records() method (pair=@n1k0)

---

.babelrc
package.json
src/batch.js
src/endpoint.js
src/index.js
src/requests.js
src/utils.js
test/api_test.js
test/batch_test.js
test/endpoint_test.js
test/integration_test.js
test/requests_test.js
test/utils_test.js

This is now ready for preliminary review.
r=? @leplatrem

Refactored batch API and global architecture

---

src/index.js
test/api_test.js
test/integration_test.js

Added support for default bucket option at the instance level.

---

src/index.js
src/requests.js
test/api_test.js
test/integration_test.js
test/requests_test.js

Added Api#updateRecord.

---

src/index.js
test/api_test.js
test/integration_test.js

Added Api#getCollection().

---

src/batch.js
src/endpoint.js
src/http.js
src/index.js
src/requests.js
src/utils.js

Learned of a bunch of syntax tricks to generate better esdocs, eg. options object detailed params:
r=? @almet

Improved and fixed esdocs.

---

package.json
src/index.js
test/api_test.js

Fixes #19: Rename KintoApi to KintoClient.

---

src/chain.js
src/index.js
test/integration_test.js

Fixes #26: Excluded internal methods from esdocs.

---

README.md
src/collection.js
test/collection_test.js
test/integration_test.js

r=? @leplatrem @Natim @almet @magopian (first in served first (please don't fight))

Added support for records list filtering.

---

test/integration_test.js
test/server_utils.js

Fixes #39: Fixed test server startup timeouts.

---

src/requests.js
test/integration_test.js
test/requests_test.js

Fixes #49: createRecord() should perform PUT when id is provided.

---

test/kinto.ini

Add default bucket plugin in integration tests server

---

README.md
package.json

https://github.com/Kinto/kinto-client/blob/add-toc-to-readme/README.md

Added TOC to README.

---

package.json

* Added TOC to README (#74)
* Add a directive to build an ES6 version for Gecko (#75)

Bump v0.6.0

---

README.md
src/collection.js
test/integration_test.js

Remove mentions of Cliquet

---

README.md
src/base.js
src/http.js
test/api_test.js

Propagate and document timeout option (fixes #84)

---

README.md

Document constructors options (fixes #69)

---

README.md

Document patch option (fixes #79)

---

README.md
src/base.js

Document server info (fixes #80)

---

src/collection.js
test/collection_test.js

Safety check on since value (fixes #51)

---

README.md
src/http.js
test/http_test.js

Minimal solution for retry-after (ref #34)

---

src/base.js
test/api_test.js

Refs #97. r=? @Natim @leplatrem

Fixes #97: Prevent registering HTTP events in batch clients.

---

.travis.yml
src/requests.js
src/utils.js
test/batch_test.js
test/integration_test.js
test/requests_test.js

setPermissions/setData bug (fixes #91)

---

src/base.js
src/bucket.js
src/collection.js
src/endpoint.js
src/requests.js
src/utils.js
test/api_test.js
test/batch_test.js
test/bucket_test.js
test/collection_test.js
test/endpoint_test.js
test/integration_test.js
test/requests_test.js

Refactor requests

---

src/bucket.js
src/collection.js
test/bucket_test.js
test/collection_test.js

Fix last_modified not being taken from object in deleteRecord()

---

src/utils.js
test/utils_test.js

Add check capability decorator

---

README.md
fx-src/jsm_prefix.js
package.json

Rename to kinto-http.js

---

src/errors.js

Add hint when server is readonly (fixes #56)

---

src/base.js
src/bucket.js
src/collection.js
src/http.js
src/requests.js

Denote optional parameters (fixes #25)

---

README.md
src/collection.js
test/collection_test.js

Remove quotes from last_modified attribute in listRecords()

---

package.json

```
**Breaking changes**
- Remove quotes from `last_modified` attribute in listRecords() result (fixes #109) (#110)
- Expose `KintoClient()` constructor in browserify builds (fixes #77) (#105)
**New features**
- Add hint when server is readonly (fixes #56) (#106)
```
@n1k0 r?

Bump v2.0.0

---

README.md

Selection a collection documentation — Fixes #113

---

.travis.yml

Upgrade to Kinto 3.3.0

---

.travis.yml

Upgrade Kinto Server version.

---

README.md
src/base.js
src/bucket.js
src/collection.js
test/api_test.js
test/bucket_test.js
test/collection_test.js
test/integration_test.js

Generalize list signatures

---

src/base.js
test/api_test.js

Fix #124: Fake headers object in batch list operations.

---

.travis.yml
README.md
src/bucket.js
src/endpoint.js
test/integration_test.js
test/kinto.ini

* Wait for release of https://github.com/Kinto/kinto/issues/773
* Wait for release of https://github.com/Kinto/kinto/issues/774
@n1k0 r?

Add listHistory() on buckets

---

src/base.js

add missing batch option documentation

---

src/batch.js
test/batch_test.js

Fixes https://github.com/Kinto/kinto.js/issues/540
@n1k0 r?

Agregated batch: provide id and path in skipped attr

---

README.md

Add upgrading docs

---

.travis.yml

Upgrade tests to kinto 4.3

---

.travis.yml
src/requests.js
test/integration_test.js
test/requests_test.js

Fix #147: safe creation of attachment

---

.travis.yml
src/collection.js
src/requests.js
src/utils.js
test/requests_test.js
test/utils_test.js

Support the attachment gzipped option.

---

fx-src/jsm_prefix.js

Fix Gecko unknown symbol

---

README.md

Added README section for polyfills as discussed in #149

Add polyfill notes for IE. Fix #149

---

src/base.js
src/http.js
test/api_test.js

Disable timeouts by default

---

.travis.yml
src/collection.js

Tests were not running on Travis. This should fix it.

Fix Travis test setup.

---

.eslintrc
.travis.yml
README.md
package.json
src/base.js
src/batch.js
src/bucket.js
src/collection.js
src/endpoint.js
src/errors.js
src/http.js
src/index.js
src/requests.js
src/utils.js
test/api_test.js
test/batch_test.js
test/bucket_test.js
test/collection_test.js
test/endpoint_test.js
test/http_test.js
test/integration_test.js
test/kinto.ini
test/requests_test.js
test/setup-jsdom.js
test/test_utils.js
test/utils_test.js

[Prettier](https://github.com/prettier/prettier) is pretty. Let's use it.

Prettierify code.

---

README.md
src/base.js
test/api_test.js
test/integration_test.js

Refs #169. Add support for paginating the list of permissions.

Refs #169: Add support for paginating permissions.

---

package.json

New features:
- Introduce add/remove permissions operations (#176)
Bug fixes:
- Refactor options so we can work with Kinto 7.0.0 (#180)
Cleanups:
- Migrate asynchronous code to async/await (#174)
- Various intermittent test failures (22a1877f82ee5e412fc1757c69649c713f6357fa, ecde4c998e6c4421d62d9f4ebd9071032de5962b)
- Check for snapshot history data availability (#173)
- Improve test server crash reporting, allow using external server (#175)

Prepare 4.3.0

---

src/index.js

Fix https://github.com/Kinto/kinto/issues/1190

Fix missing babel-polyfill.

---

package.json
src/base.js
src/batch.js
src/http.js
src/requests.js
src/utils.js
test/api_test.js
test/integration_test.js
test/setup-jsdom.js
test/utils_test.js

Updated prettier to 1.0.0. I like the improved coding style.

Updated prettier to 1.0.0.

---

README.md
package.json
src/collection.js
test/collection_test.js

Make sure to handle patch option for collection setData.

---

package.json

* Fix test.
* EventEmitter was moved (#190)

Bump v4.3.4

---

package.json
src/base.js
src/batch.js
test/integration_test.js

Upgrade prettier to 1.4.2.

---

package.json
src/requests.js

Bump prettier to 1.5.1

---

package.json
src/batch.js

chore(package): update eslint to version 4.1.1

---

README.md

Fix ES5 import.

---

test/integration_test.js

This is the same as #207 but for some other call sites.

Fix other intermittent tests

---

.pre-commit-config.yaml
README.md
package.json

This is the same as https://github.com/Kinto/kinto.js/pull/737, but
for this project.

Use pre-commit

---

package.json
test/api_test.js
test/batch_test.js
test/bucket_test.js
test/collection_test.js
test/integration_test.js
test/requests_test.js

Fix the breakage that ensues when you bump a minor.
Fixes #228.

Greenkeeper/prettier 1.6.0

---

.pre-commit-config.yaml
package.json
test/api_test.js
test/batch_test.js
test/bucket_test.js
test/collection_test.js
test/endpoint_test.js
test/http_test.js
test/integration_test.js
test/requests_test.js
test/utils_test.js

Update prettier to v1.7.1

---

package.json
test/api_test.js
test/batch_test.js
test/bucket_test.js
test/collection_test.js
test/endpoint_test.js
test/http_test.js
test/integration_test.js
test/requests_test.js
test/utils_test.js

Greenkeeper/prettier 1.7.2

---

package.json
src/base.js

Update prettier to 1.8.1.
This should help address e.g. #252.

Update prettier to 1.8.1

---

.babelrc
package.json
src/errors.js
src/http.js
test/http_test.js

This is meant to address #254, #235, #193, #192, https://bugzilla.mozilla.org/show_bug.cgi?id=1388830, https://bugzilla.mozilla.org/show_bug.cgi?id=1415222, and maybe others.

Cleanup error handling

---

package.json

* Update dependencies (#194, #197, #198, #199, #200, #202, #206, #204,
#208, #212, #216, #220, #219, #218, #223, #224, #226, #227, #229,
#231, #232, #233, #234, #236, #239, #241, #244, #245, #246, #250,
#253, #249). Finally convert eslint dependency into a range
dependency (#238).
* Fix intermittent test (#207)
* Fix ES5 import. (#211)
* Fix other intermittent tests (#214)
* Use pre-commit (#215)
* Ensure that KINTO_EOS is a string (#248)
* Require babel-polyfill only when not loaded already. (#255)
* Cleanup error handling (#256)

Bump 4.4.0

---

package.json

* Add a couple more tests for #235
* Firefox updates (#258)
* Use transform-runtime to request regenerator without depending on it (#260)

Prepare v4.4.1

---

package.json

Upgrade eslint to 4.14.0

---

.babelrc
fx-src/index.js
fx-src/jsm_prefix.js
package.json
src/base.js
src/utils.js

Another attempt to build a version of this library for inclusion in Firefox, plus taking care of #225 now that all the dependencies are in place. To make this transition smoother, we make some changes here to mirror changes that have been made to our compiled output in the Firefox source tree.

Firefox updates

---

package.json

Bump v4.5.3

---

package.json
src/collection.js

Bump to prettier 1.12.0

---

fx-src/index.js
fx-src/jsm_prefix.js

Import some changes that were made downstream in Firefox to code that lives in `fx-src`.

Firefox compatibility

---

README.md
src/base.js
src/bucket.js
src/collection.js
src/utils.js
test/api_test.js
test/bucket_test.js
test/collection_test.js
test/utils_test.js

Support more queries

---

.travis.yml
README.md
src/bucket.js
src/collection.js
test/bucket_test.js
test/collection_test.js

Retrieve timestamps (ETag) of plural endpoints

---

fx-src/index.js

As per https://hg.mozilla.org/mozilla-central/log/9ee669c657c79b26a6ec0df246cc5bfe2b1d9a9a/services/common/kinto-http-client.js

Backport ChromeUtils.import() changes

---

src/utils.js
test/setup-jsdom.js
test/utils_test.js

Attempt to address #468. There may be other NodeJS problems, but let's take them one at a time.

If Blob is not present, use Buffer

---

package-lock.json
package.json
rollup.config.js

Reverts Kinto/kinto-http.js#890

Revert "Bump rollup to v2"

---

package-lock.json
package.json

This PR updates rollup to the latest v2 release.

Update rollup to latest v2

---

package-lock.json
package.json

This PR updates @rollup/plugin-commonjs to the latest version.

Update @rollup/plugin-commonjs to latest

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/lint.yml

This PR adds new GHA workflows to mirror what we're testing in Travis (basically a new Linux integration workflow and a workflow to check Prettier/ESLint).

Migrate Travis CI steps to GitHub Actions

---

src/index.ts
src/types.ts

This PR exports the PermissionData type and narrows the HistoryEntry.action type.

Export PermissionData type and narrow HistoryEntry.action type

---

package-lock.json
package.json

This PR updates our package-lock.json file to the new npm v7 structure.

Update to npm v7
