- src/index.js
- test/api_test.js
Atm if you want to have a local EventEmitter instance created for you and provide custom options, you need to write something like this:
```js
const api = new Api("http://foo", undefined, {requestMode: "cors"})
```
There's no point at providing an undefined second arg, so we should just do:
```js
const api = new Api("http://foo", {requestMode: "cors"})
```
And if we want to provide a custom event emitter:
```js
const events = new EventEmitter();
const api = new Api("http://foo", {events, requestMode: "cors"})
```
r=? @leplatrem
> [BC break] Pass events as an option instead of a required argument.

- package.json
- test/integration_test.js
- test/kinto.ini
- test/server_utils.js
This sets up the integration environment using a real Kinto server.
Next steps are to extract the `KintoServer` test utility class to its own package so we can conveniently reuse it in Kinto.js as a dev dependency.
r=? @leplatrem
> Initial integration test setup

- src/index.js
- src/requests.js
- test/api_test.js
Refs #14. r=? @leplatrem @almet 
Note: this also adds support for a default `safe` option which was not available at the instance level.
> Better client request options handling.

- package.json
When trying to publish a new version of the package on npmjs.com, I had to run `npm run build` and `npm run dist`, I've had different issues:
1. Apparently there is a need to not install the `babel` package:
```
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.
npm uninstall babel
npm install babel-cli
See http://babeljs.io/docs/usage/cli/ for setup instructions.
```
2. After doing this, a package was missing, I had to do `npm install line-numbers` manually.
3. Then, the binaries for babel and browserify weren't found, so I had to put the relative path to them.
Now, I'm not sure this is how it's supposed to be handled (I would prefer to find a way to let the name of …
> Remove the babel dependency

- README.md
- src/chain.js
- test/chain_test.js
Refs #27. Docs for TL;DRThePatchFully:
Both `bucket()` and `collection()` methods accept an `options` object as a second arguments where you can define the following options:
- `{Object} headers`: Custom headers to send along the request;
- `{Boolean} safe`: Ensure safe transactional operations; read more about that below.
Sample usage:
```js
client.bucket("blog", {
headers: {"X-Hello": "Hello!"},
safe: true
});
```
Here the `X-Hello` header and the `safe` option will be used for building every outgoing request sent to the server, for every collection attached to this bucket.
This works at the collection level as well:
```js
client.bucket("blog")
.collection("posts", {
headers: {"X-Hello": "Hello!"},
safe: true
});
```
Every request sent for this collection will have the options applied. …
> Fixes #27: Added support for options to Bucket and Collection.

- README.md
- src/collection.js
- src/utils.js
- test/collection_test.js
- test/integration_test.js
- test/utils_test.js
This patch adds support for paginating the list of records.
**Note:** This changes the API for `Collection#listRecords`, as it now requires to resolve with an Object exposing the pagination API instead of the list of records directly.
Excerpt from added docs:
All records are retrieved by default. To specify a max number of records to retrieve, you can use the `limit` option:
```js
client.bucket("blog").collection("posts")
.listRecords({limit: 20})
.then(result => ...);
```
To fetch the following batch of results, just call `next()` from the result object obtained. If no next page is available, `next()` throws an error you can catch to exit the flow:
```js
client.bucket("blog").collection("posts")
.listRecords({limit: 20})
.then(({data, next}) => {
try {
return next();
} catch(err) { …
```
> Paginate records list

- README.md
- src/collection.js
- src/index.js
- src/requests.js
- src/utils.js
- test/api_test.js
- test/collection_test.js
- test/integration_test.js
- test/utils_test.js
r=? @leplatrem
```js
client.bucket("blog").collection("posts")
.listRecords()
.then(result => ...);
```
Sample result:
```js
{
last_modified: "\"1456183930780\"",
next: <Function>,
data: [
{
"content": "True.",
"last_modified": 1456183930780,
"id": "a89dd4b2-d597-4192-bc2b-834116244d29",
"title": "I love cheese"
},
{
"content": "Yo",
"last_modified": 1456183914275,
"id": "63c1805a-565a-46cc-bfb3-007dfad54065",
"title": "Another post"
}
]
}
```
Note the root `last_modified` value which is the [collection's timestamp](http://kinto.readthedocs.org/en/latest/api/1.x/cliquet/timestamps.html). This value is opaque and should be reused as is, eg. passing it as a `since` option (see the *Options* section below).
By default, records are listed by `last_modified` descending order. You can set the …
> Closes #47: Added support for since to listRecords.

- src/index.js
- test/api_test.js
- test/collection_test.js
I'm really challenging the benefits of this. Do we have an exhaustive list of exposed server settings documented somewhere, so we can accurately challenge future usefulness of this patch? /cc @leplatrem
> Fixes #55: Fetch server settings on first issued HTTP request.

- src/index.js
- test/api_test.js
- test/integration_test.js
This patch exposes new methods to lazily retrieve and cache exposed server configuration:
- `#fetchCapabilities()` resolves with the server `capabilities` object.
- `#fetchUser()` resolves with the server `user` object.
- `#fetchHTTPApiVersion()` resolves with the server `http_api_version` object.
- `#fetchServerSettings()` works as before.
r=? @leplatrem
> Fixes #57, #58, #59: Server config attribute getters.

- .babelrc
- package.json
- src/index.js
- src/requests.js
- src/utils.js
- test/api_test.js
- test/integration_test.js
- test/requests_test.js
- test/server_utils.js
- test/test_utils.js
- test/utils_test.js
This is WiP, refs #62.
The patch introduces a `ensureSupported` method at the client level we can leverage to conditionally execute a function depending of HTTP API version requirements.
This also adds `KintoClient#deleteBuckets()` which is provided by the Kinto protocol v1.4 only, and conditional integration tests for it. 
Feedback=? @almet @Natim @leplatrem @magopian 
PS: Discarded using ES7 decorators. I really wish decorated methods could access their related instance state, though we're only passed the class itself, which is pointless except if you want to attach static properties to it (which you don't). Also, fought too hard with Babel to be confident using them securely.
Edit: Finally managed to use ES7 decorators. Much better.
> Fixes #62: Check for http_api_version compatibility.

- package.json
- Merged #72: Revamped batch API.
- Fixed #62: Added checks for server current `http_version_api` support.
- Fixed #68: Updated delete endpoint methods to not send JSON body data anymore. 
- Merged #61: Added `KintoClient#fetchServerInfo`, `KintoClient#fetchServerCapabilities`, `KintoClient#fetchUser` and `KintoClient#fetchHTTPApiVersion`.
> Bump v0.5.0.

- README.md
- src/base.js
- src/bucket.js
- src/requests.js
- test/api_test.js
- test/bucket_test.js
- test/integration_test.js
- test/requests_test.js
Refs #71.
Note that this introduces yet another convention with `setData` while we already have `getAttributes`, `setMetadata` and friends. I'm panning to work on homogeneizing all this mess in a followup PR, where `getData` and `setData` will be the common convention (refs #83).
r=? @Natim @leplatrem
> Fixes #71: Allow posting bucket data.

- README.md
- src/base.js
- src/bucket.js
- src/collection.js
- src/requests.js
- src/utils.js
- test/bucket_test.js
- test/collection_test.js
- test/integration_test.js
- test/requests_test.js
@n1k0 please review thoroughly :)
```
**Breaking changes**
- `client.bucket(...).getData()` now returns the `data` object instead of both data and permissions
- `Collection#setSchema()` and `Collection#getSchema()` were dropped. 
- `Collection#getAttributes()` was splited into `Collection#getData()` and `Collection#getPermissions()`
- `Collection#getMetadata()` is now `Collection#getData()`
- `Collection#setMetadata()` is now `Collection#setData()`
```
> Rename methods for consistency (fixes #83)

- .travis.yml
- README.md
- package.json
- src/base.js
- src/collection.js
- src/endpoint.js
- src/http.js
- src/requests.js
- src/utils.js
- test/api_test.js
- test/http_test.js
- test/integration_test.js
- test/kinto.ini
- test/requests_test.js
- test/setup-jsdom.js
- test/utils_test.js
WiP, refs #104, cc @leplatrem.
I'm stuck here with this kinto server error https://github.com/Kinto/kinto-attachment/issues/100
It's certainly a problem with the patch implementation as attaching a file using httpie and the kinto admin both work just fine. It may be related to jsdom's `FormData` implementation.
I'd be happy to get some help here.
> Fix #104: Add support for the attachment API.

- src/collection.js
- src/http.js
- src/requests.js
- test/http_test.js
- test/integration_test.js
- test/kinto.ini
- test/requests_test.js
Refs #119. This is ugly, but I couldn't find any better generic way to check for a multipart request body :disappointed:  
Tested the patch on kinto-admin, solves the issue.
r=? @leplatrem
> Fix #119: Ensure a multipart Content-Type header is used when sending attachments.

- README.md
- src/base.js
- src/endpoint.js
- test/api_test.js
- test/endpoint_test.js
- test/integration_test.js
- test/kinto.ini
refs #122, r=? @leplatrem 
If the [`permissions_endpoint` capability](http://kinto.readthedocs.io/en/stable/api/1.x/permissions.html#list-every-permissions) is installed on the server, you can retrieve the list of all permissions set for the authenticated user using the `listPermissions()` method:
```js
client.listPermissions([options])
.then(result => ...);
```
Sample result:
```js
{
"data": [
{
"bucket_id": "mybucket",
"id": "mybucket",
"permissions": [
"write",
"read",
"group:create",
"collection:create"
],
"resource_name": "bucket",
"uri": "/buckets/mybucket"
},
...
]
}
```
> Fix #122: Add support for the /permissions endpoint.

- README.md
- src/base.js
- test/api_test.js
- test/integration_test.js
Alternative proposal to #130.
Feedback=? @Natim @leplatrem @glasserc
> Expose a hasNextPage property to the list results object.

- src/errors.js
This slightly improves the error message attached to a 412 error response. The old one was accurate but could be misleading. 
r=? @Natim
> Improve HTTP 412 error message.

- README.md
- src/base.js
- src/collection.js
- test/api_test.js
- test/collection_test.js
- test/integration_test.js
Refs #135. r=? @Natim  @glasserc 
```js
client.bucket("blog").collection("posts")
.listRecords()
.then(result => ...);
```
Sample result:
```js
{
last_modified: "1456183930780",
next: <Function>,
totalRecords: 2,
data: [
{
"content": "True.",
"last_modified": 1456183930780,
"id": "a89dd4b2-d597-4192-bc2b-834116244d29",
"title": "I love cheese"
},
{
"content": "Yo",
"last_modified": 1456183914275,
"id": "63c1805a-565a-46cc-bfb3-007dfad54065",
"title": "Another post"
}
]
}
```
The result object exposes the following properties:
- `last_modified`: the [collection's timestamp](http://kinto.readthedocs.io/en/stable/api/1.x/timestamps.html). This value is opaque and should be reused as is, eg. passing it as a `since` option (see [Generic bucket and collection …
> Fix #135: Allow retrieval of collection total number of records.

- .travis.yml
- README.md
- src/base.js
- src/collection.js
- test/integration_test.js
- test/kinto.ini
This adds a new `at` option to `Collection#listRecords` to retrieve a snapshot of the collection records at a given timestamp in the past.
f=? @leplatrem
> Add support for a 'at' collection listRecords filter.

- esdoc.json
- package.json
- test/kinto.ini
Per https://github.com/esdoc/esdoc/issues/390, esdoc-es7-plugin is
deprecated and esdoc has itself grown functionality equivalent to
it. Now using esdoc-es7-plugin causes esdoc generation to fail.
Following the fix in the linked issue, just turn on all the options,
since I'm not sure which ones we use specifically.
Thanks tiberiuichim for reporting this issue on Slack.
> esdoc: remove esdoc-es7-plugin

- package.json
This installs a git precommit hook for linting and formatting code against prettier configuration.
> Install git precommit hook for linting and formatting.

- .babelrc
- package.json
- src/base.js
- src/bucket.js
- src/collection.js
- src/http.js
- src/utils.js
- test/api_test.js
- test/bucket_test.js
- test/collection_test.js
- test/http_test.js
- test/test_utils.js
- test/utils_test.js
Migrate our current async source code to use [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).
Notes:
- The http.js module preliminary refactoring has been isolated in a [single commit](https://github.com/Kinto/kinto-http.js/pull/174/commits/23f376e8e367e82566dcdbd8a0dd1508ef373e97) to ease the review process.
- The diff is slightly larger mostly because of that large http.js module refactoring.
> Async await

- README.md
- src/collection.js
- test/integration_test.js
This adds checks to ensure we dispose of all the history required to compute a snapshot back to requested timestamp.
Refs https://github.com/Kinto/kinto-admin/issues/402
> Check for snapshot history data availability.

- .travis.yml
- README.md
- test/integration_test.js
This patch improves Kinto test server crash reporting for better debuggability:
> Improve test server crash reporting, allow using external test server

- README.md
- src/base.js
- src/bucket.js
- src/collection.js
- src/http.js
- src/utils.js
- test/api_test.js
- test/bucket_test.js
- test/collection_test.js
- test/http_test.js
- test/integration_test.js
Per #178 and https://github.com/Kinto/kinto-admin/issues/421, kinto-admin broke when running against Kinto 7.0.0. Batch requests were being constructed with random arguments like `safe`, `retry`, and `batch`, which aren't request arguments but generic "options" for clients, buckets, and collections. Previously this wasn't a problem, but in Kinto 7.0.0, we now validate requests against a colander schema, and the colander schema doesn't recognize these options. Rather than hacking up a quick fix like 1. permitting the request schema in Kinto server to allow these unknown arguments or 2. explicitly `omit`ting these specific unknown arguments when generating requests, I took the opportunity to dive into the codebase and clarify options throughout the three classes, promoting everything out of …
> Refactor options so we can work with Kinto 7.0.0

- src/base.js
- src/utils.js
- test/api_test.js
- test/utils_test.js
This fixes an issue preventing request to be handled properly in Google Chrome. Chrome expects fetch options like `method` to be always defined. We may pass `undefined` instead, which results in this:
I know @glasserc loves JavaScript, so I'd really like him to review this patch.
> Fix undefined request options passed to fetch.

- src/base.js
- test/api_test.js
- test/collection_test.js
Try to clean up some of the warts around the use of `serverInfo`. In particular:
- Don't memoize the result of `fetchUser`, since it can change in the presence of authentication information.
- Forbid the passing of `headers` to `fetchServerInfo`, since it doesn't make any sense (the server information shouldn't change according to the presence of authentication information).
- Get rid of a needless `fetchServerSettings` in `execute()`.
- Pass `retry` to one call to `fetchServerSettings` that didn't have it.
This doesn't completely clean it up; `retry` isn't passed in calls made via `capable()` or `support()`, and I don't see a way to make it be. Honestly I'd prefer to get rid of `retry` as an option on every single method, but that's a separate discussion.
Fixes #181 and responds to …
> Cleanup serverInfo a little bit

- fx-src/index.js
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1356231, devtools is
going away. Update kinto-http.js to match.
Probably this is a signal that we shouldn't have Firefox-specific goop
in this repo.
> EventEmitter was moved

- test/integration_test.js
There appears to be a race condition here (see
https://github.com/Kinto/kinto/issues/1290), although this being the
memory backend, we probably shouldn't expect anything robust. Work
around it by making requests sequentially.
> Fix intermittent test

- package.json
This got pinned to a specific version in
b3d4e280c3f66ceea496c4368546d602c6c11916 to work around a temporary
breakage that seems to have been resolved at some point in the
intervening 18 months. Most eslint versions have not caused breakage.
Closes #237.
> Turn eslint dependency into range dependency

- test/integration_test.js
Kinto's environment parsing logic runs this through native_value,
which tries to parse it using ast.literal_eval, which interprets the
string "2017-10-30" as the mathematical expression 2017-10-30, which
is 1977.
This code has been in place for a long time so it isn't clear how it
ever worked. ast.literal_eval has behaved this way since at least
2014.
In Kinto 7.x, we stopped using literal_eval for native values and
instead use json.loads, which of course can't parse 2017-10-30, which
leads us to fall back to using the string as a string. So the recent
test failures we've been seeing have only affected Kinto 6.0.4.
One reason why this seems to have been working up until very recently
is that 2017-10-10 is the first date since 2016-12-31 where one of the
"operands" didn't start with a 0, …
> Ensure that KINTO_EOS is a string

- .babelrc
- fx-src/index.js
- src/errors.js
While working on https://bugzilla.mozilla.org/show_bug.cgi?id=1388830 and https://bugzilla.mozilla.org/show_bug.cgi?id=1415222, I discovered that actually using the exception classes from 4.4.0 didn't actually work. This PR represents some of the changes I've had to make in order to get things closer to working in Gecko.
> Firefox updates

- .babelrc
- package.json
- src/index.js
[transform-runtime](https://babeljs.io/docs/plugins/transform-runtime) is meant to allow us to access the regenerator
polyfill "seamlessly, without global pollution". This means we don't
need to import it explicitly, and we don't need to make any efforts to
import it only once.
This replaces babel-polyfill, which is meant for applications, not
libraries.
Applications are responsible for providing the polyfill.
We use the "polyfill: false" option to disable conversion of "builtin"
JS methods such as Array.from and Object.create, which we could also
rewrite except for
https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend/issues/15.
This is meant to fix #259 and Kinto/kinto#1379.
Refs #159 (cc: @screendriver).
Refs Kinto/kinto-admin#456 and Kinto/kinto-admin#446.
> Use transform-runtime to request regenerator without depending on it

- test/api_test.js
- test/bucket_test.js
- test/collection_test.js
- test/http_test.js
- test/integration_test.js
Combines with https://github.com/Kinto/kinto/pull/1576 to fix the current test failures in Travis.
Also, while we're here, fix the test warnings from the sinon version.
> Fix testing

- test/kinto-6.0.1.ini
- test/kinto.ini
This is another crack at #304. Rather than move everything to accounts as the One True Path, let's just try to stop the bleeding (where bleeding = constantly failing tests), and then roll in other stuff as necessary.
> Force basicauth in tests on master

- src/collection.js
- test/collection_test.js
Ref #307.
This represents a minimal change that fixes the issue. In particular, it doesn't add support for `_fields` (which should probably be supported as a separate `option`) and it doesn't add support to query arguments for buckets, records, or groups (are there other resources too?). The goal of this PR is to land just this feature for the purposes of getting uplifted.
> Add support for query arguments to Collection#getData

- .travis.yml
- src/base.js
- src/requests.js
- test/integration_test.js
- test/kinto-8.1.2.ini
- test/kinto.ini
This is meant to extract the part of #304 that adds a `createAccount` method, and nothing besides that.
I had a horrible realization when I was writing this that when adding the `accounts` plugin was going to make the entire test suite slow, even for those tests that do `basicauth`. Fortunately, it doesn't; see https://github.com/Kinto/kinto/issues/1821. Still, we might want to hold off on merging this until we figure out our plan for that bug.
Another option might be to use a separate config for just the account tests. But then we might have to have two, one for each Kinto version..
> Add accounts support

- test/integration_test.js
This change has been in Kinto for over a year (since version
2.0.0). It's true for every version we test against.
Fixes #311.
> Don't gate delete-buckets on HTTP API version

- .travis.yml
This got dropped soon after it got added, but it seems like this is
why we fetch versions.txt. It's my hope that putting this back in will
cause tests to pass (right now they're failing because kinto relies on
jsonschema==3.0.0a3 and we're installing 2.6.0).
> Restore use of versions.txt when installing master

- src/base.js
- test/api_test.js
- test/integration_test.js
This got removed in https://github.com/Kinto/kinto/pull/1931, and has
been causing failing tests ever since.
This appears to be the cause of build failures in https://github.com/Kinto/kinto-http.js/issues/320 and #321.
Fixes #322.
> Remove support for the Total-Records header on GET

- src/http.js
- src/utils.js
- test/http_test.js
Fix #471
There were many ways to solve this... I could have obfuscated the value in the error constructor, could have removed the options from the logging message, etc. 
Let me know what do you think!
> Fix #471: obfuscate authorization header values in errors

- package.json
The ES module import path is `lib/esm/index.js`, not `lib/es/index.js`.
@leplatrem once this is merged would you mind doing another alpha release on NPM? For now I'm manually changing it inside my `node_modules` folder.
> Fix ES module import path

- .travis.yml
- tsconfig.json
`Headers.entries()` returns an `IterableIterator<[string, string]>`. Iterators are an ES6 feature, so the TypeScript compiler has to be explicitly told to convert them to something ES5 environments can understand. This PR enables that option, `downlevelIteration` in `tsconfig`.
Also, to prevent something like this from happening again, `npm run build` has been added to the list of actions for Travis.
> Enable down-level iteration

- README.md
This replaces the non-functional Greenkeeper badge with a Dependabot one since that's what we're using anyway.
Plus it looks nicer than a broken image :)
> Replace Greenkeeper badge with Dependabot badge

- src/base.ts
- src/bucket.ts
- src/collection.ts
- test/api_test.ts
- test/bucket_test.ts
After my [previous PR](https://github.com/Kinto/kinto-http.js/pull/503), I did a bit of research to see if there was a better way to access private properties during unit tests. Lo and behold, there is! Apparently, there's an [explicit escape hatch](https://github.com/microsoft/TypeScript/issues/19335) specifically for this purpose.
This PR removes the added getters, replacing them with bracket notation in tests.
While removing the getters, the TypeScript compiler discovered that the `_isBatch` property on `Bucket` and `Collection` is never read; in fact, it's also not read in `kinto.js`. As such, I've removed the property from `Bucket` and `Collection`. The property still exists on `KintoClientBase`, so in theory if someone really wanted to know the value they could do something like …
> Convert private property access to bracket notation

- .eslintrc
- src/base.ts
- src/batch.ts
- src/bucket.ts
- src/collection.ts
- src/http.ts
- src/types.ts
- src/utils.ts
- test/.eslintrc
This PR adds explicit return types to class methods and functions. Since it's just adding the types that the TypeScript compiler is already inferring, this doesn't actually change any functionality.
It also activates an eslint rule requiring all functions and class methods to explicitly declare their return types.
The primary motivator for this is to make it apparent to the developer what the return type of the function is, and to ensure that they don't accidentally modify the return type without realizing it. It also points out where we're being fast and loose with the typings, resulting in return types that look like `Promise<unknown>` and `Promise<KintoResponse<unknown>>`. These return types are still type-safe since trying to access properties on `unknown` will throw a compiler error, …
> Add explicit function return types

- .gitattributes
- .github/workflows/windows-ci.yml
This PR adds a GitHub Action that runs the tests on Windows. It also adds a `.gitattributes` file forcing git to always use LF line endings regardless of Git's settings.
Fixes #519.
> Add Windows CI GitHub Workflow

- package-lock.json
- package.json
- src/base.ts
- src/http.ts
- src/index.ts
- src/types.ts
- test/api_test.ts
- test/http_test.ts
This PR replaces our usage of EventEmitter with an interface with the following shape:
```ts
interface Emitter {
emit(type: string, event?: any): void;
on(type: string, handler: (event?: any) => void): void;
off(type: string, handler: (event?: any) => void): void;
}
```
This allows the consumer to provide their own emitter, or opt not to. For users who opt to use a small emitter like [mitt](https://github.com/developit/mitt), this should result in a decently smaller bundle size.
I also updated the `HTTP` tests to run the entire suite with an `EventEmitter`, with `mitt`, and without an event emitter at all.
Fixes #679
> Replace EventEmitter with interface and make it optional

- .npmignore
- package.json
- tsconfig.json
This PR cleans up which files we publish to NPM by switching from a `.npmignore` blacklist to a `package.json` `files` whitelist.
I also adjusted the build script to reflect the fact that we're building the Node bundle with rollup, which means we no longer need TypeScript to emit a CommonJS version.
> Cleanup published files

- src/index.ts
This PR removes the type-only import of `Collection` since the tests for `kinto.js` rely on having access to the prototype. It also re-exports SUPPORTED_PROTOCOL_VERSION.
> export SUPPORTED_PROTOCOL_VERSION and Collection

- .github/workflows/size.yml
This PR adds a GitHub workflow that will report the compressed size of our bundles on each PR made from a branch in this repo. (Sadly due to the way GitHub Actions handles forks, it won't report when a PR is made from a fork. I have an idea on how we might make that a little better, but for now this is acceptable.
> Add compressed-size-action workflow

- src/base.ts
- src/bucket.ts
- src/collection.ts
- test/bucket_test.ts
- test/collection_test.ts
Instead of having:
```js
const client = new KintoClient(..);
const clientColl = client.bucket(bid).collection(cid);
await clientColl.list();
await client.execute(...);
```
We could just have one reference to the collection instance and still execute raw requests.
> Expose execute in bucket and collection classes

- src/bucket.ts
- src/collection.ts
The previous approach fails with something like `this.http is undefined`
> Fix calls to client.execute() from bucket/collection

- src/base.ts
- src/bucket.ts
- src/collection.ts
- test/api_test.ts
- test/bucket_test.ts
- test/collection_test.ts
It implements deleteRecords, deleteCollections and deleteBuckets, with the same filtering as listRecords. #95
> Delete on plural endpoints

- .github/workflows/size.yml
This PR updated the compressed size action workflow to v2, which gives us the ability to specify a minimum change threshold. This will help prevent the Gecko build from showing as changed because the git hash in the file is different.
> Update compressed size action to v2

- .github/workflows/browsers.yml
- intern.json
Due to the instability of the Firefox tests on Windows, this PR shifts the platform to Linux to see if the stability is any better.
> Run browser tests on Linux

- src/collection.ts
The previous implementation was not handling properly deletions/recreations. This one is much simpler and works as expected.
> Fix implementation of collection snapshot

- src/collection.ts
- test/integration_test.ts
Unfortunately the fix in #956 was not enough to cover the misbehavior of the Admin UI diff view. I traced it back and it was related to the fact that plural deletes do not generate history entries.
This approach seems to work as expected, and does not introduce too much performance loss
Fixes #963
> Fix #963: Fix snapshot when records were deleted via plural endpoint

- src/base.ts
- src/errors.ts
- src/http.ts
- src/types.ts
- test/test_utils.ts
This PR adds more specific TypeScript types to the `fetchFunc` option.
Using `Function` is the same as `(...args: any) => any`, meaning that any function would be accepted as a valid `fetchFunc`. With this PR, the supplied function will need to conform to the minimal `fetch` interface. Essentially, functions will need to have the following properties:
```ts
export interface FetchHeaders {
keys(): IterableIterator<string> | string[];
entries(): IterableIterator<[string, string]> | [string, string][];
get(name: string): string | null;
has(name: string): boolean;
}
export interface FetchResponse {
status: number;
statusText: string;
text(): Promise<string>;
headers: FetchHeaders;
}
export type FetchFunction = (
input: RequestInfo,
init?: RequestInit | undefined
) => Promise<FetchResponse>; …
```
> Add TypeScript types to fetchFunc option

- fx-src/jsm_prefix.js
- src/base.ts
- src/errors.ts
- src/http.ts
- src/types.ts
- test/api_test.ts
- test/collection_test.ts
- test/http_test.ts
- test/test_utils.ts
/cc @mixedpuppy
Preliminary work for https://bugzilla.mozilla.org/show_bug.cgi?id=1654693
> Add fetchFunc option to client constructor

- .github/workflows/browsers.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/windows-ci.yml
Closes #1190 since the [`ubuntu-latest`](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211122.1) and [`windows-latest`](https://github.com/actions/virtual-environments/releases/tag/win19%2F20211122.1) runners now ship with Chrome Driver version 96 (at the time of this PR).
Since these images also [now ship with `Node v16 (LTS)`](https://github.com/actions/virtual-environments/issues/4446) and have shipped with `Python 3.x` for a while, those steps have been removed from action config.
> Remove unneeded Github Action steps
